#!/usr/bin/env bash
#
# null-test.sh - Runs the full null test and produces a compact report.
#
# For each phase (ceiling, app) and for each rate:
#   - starts a CPU sampler on the containers
#   - launches k6 at that rate
#   - extracts the metrics that matter from the JSON summary
#   - records the peak CPU per container during that step
#
# The final report fits on one page: it is the one to read and share.
# The full k6 logs stay in files, not on screen, because k6 emits
# a WARN line for every failed request and at 8000 req/s that is tens
# of thousands of useless lines.
#
# Usage:
#   ./load/null-test.sh
#   RATES="500 1000 2000" DURATION=20s ./load/null-test.sh
#
set -uo pipefail

HARNESS="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$HARNESS"

RATES="${RATES:-500 1000 2000 4000 8000 16000}"
PHASES="${PHASES:-ceiling app}"
DURATION="${DURATION:-30s}"
GAP="${GAP:-10}"

STAMP="$(date +%Y%m%d-%H%M%S)"
OUT="$HARNESS/results/null-test-$STAMP"
REPORT="$OUT/report.txt"

mkdir -p "$OUT"
chmod 777 "$HARNESS/results" 2>/dev/null || true

log() { printf '\033[1m==>\033[0m %s\n' "$*"; }

# --- CPU sampler ---------------------------------------------------------
# Samples every 2s into CSV. The k6 container has a name generated by
# "docker compose run", so it is normalised to "k6".

sampler_start() {
    local f="$1"
    : > "$f"
    (
        while true; do
            docker stats --no-stream --format '{{.Name}},{{.CPUPerc}}' 2>/dev/null \
              | sed 's/^undertow-k6-run-[a-f0-9]*/k6/' >> "$f"
            sleep 2
        done
    ) >/dev/null 2>&1 &
    echo $!
}

sampler_peak() {
    # Peak CPU per container, format "name=NN".
    awk -F, '{gsub(/%/,"",$2); if ($2+0 > m[$1]) m[$1]=$2+0}
             END {for (c in m) printf "%s=%.0f ", c, m[c]}' "$1"
}

annotate() {
    curl -s -X POST http://localhost:3000/api/annotations \
        -H 'Content-Type: application/json' \
        -u "admin:$(grep -oP '^GRAFANA_ADMIN_PASSWORD=\K.*' .env 2>/dev/null)" \
        -d "{\"time\":$(date +%s000),\"tags\":[\"undertow\",\"$1\"],\"text\":\"$2\"}" \
        > /dev/null 2>&1 || true
}

# --- preliminary check ----------------------------------------------------
log "checking that the stack responds"
if ! docker compose ps --status running --format '{{.Service}}' | grep -q varnish; then
    echo "ERROR: the stack is not up. Run:  docker compose up -d" >&2
    exit 1
fi

{
    echo "NULL TEST — $(date -Is)"
    echo "================================================================"
    echo
    echo "Configuration:"
    grep -E '^(CPUSET_|THREADS|BACKLOG|DB_POOL|VARNISH_SIZE)' .env | sed 's/^/  /'
    echo "  RATES=$RATES"
    echo "  DURATION=$DURATION"
    echo "  commit=$(git rev-parse --short HEAD 2>/dev/null || echo n/a)"
    echo "  nproc=$(nproc)"
    echo
} > "$REPORT"

# --- sweep ----------------------------------------------------------------
for phase in $PHASES; do
    log "phase: $phase"
    {
        echo "----------------------------------------------------------------"
        echo "PHASE $phase"
        echo "----------------------------------------------------------------"
        printf '%-8s %9s %9s %9s %8s  %s\n' \
               rate dropped reqs 'p99(ms)' 'fail%' 'peak CPU %'
    } >> "$REPORT"

    for rate in $RATES; do
        printf '    rate %s ... ' "$rate"
        tag="$phase-$rate"
        cpuf="$OUT/cpu-$tag.csv"
        k6log="$OUT/k6-$tag.log"

        annotate "$phase-$rate" "Start of step $rate req/s"

        pid=$(sampler_start "$cpuf")

        docker compose --profile load run --rm -T -T \
            -e PHASE="$phase" -e RATE="$rate" -e DURATION="$DURATION" \
            -e OUTFILE="s-$tag" \
            k6 run --quiet /scripts/null-test.js > "$k6log" 2>&1

        kill "$pid" 2>/dev/null; wait "$pid" 2>/dev/null

        sum="$HARNESS/results/s-$tag.json"
        if [[ -f "$sum" ]]; then
            mv "$sum" "$OUT/"
            sum="$OUT/s-$tag.json"
            read -r dropped reqs p99 failed <<<"$(jq -r '
                [ (.metrics.dropped_iterations.values.count // 0),
                  (.metrics.http_reqs.values.count // 0),
                  ((.metrics.http_req_duration.values["p(99)"] // 0)*10|round/10),
                  ((.metrics.http_req_failed.values.rate // 0)*1000|round/10)
                ] | @tsv' "$sum")"
        else
            dropped="?"; reqs="?"; p99="?"; failed="?"
        fi

        peak="$(sampler_peak "$cpuf")"
        printf '%-8s %9s %9s %9s %8s  %s\n' \
               "$rate" "$dropped" "$reqs" "$p99" "$failed" "$peak" >> "$REPORT"

        if [[ "$dropped" == "0" ]]; then echo "ok"; else echo "dropped: $dropped"; fi

        annotate "$phase-$rate" "End of step $rate req/s"
        sleep "$GAP"
    done
    echo >> "$REPORT"
done

# --- verdict --------------------------------------------------------------
{
    echo "================================================================"
    echo "VERDICT"
    echo "================================================================"
    for phase in $PHASES; do
        best=""
        for rate in $RATES; do
            f="$OUT/s-$phase-$rate.json"
            # dropped==0 is necessary but not sufficient: a step with a
            # p99 of 17 seconds and 3% failures describes an already
            # broken system, even if the generator held the rate.
            ok=$(jq -r '
                if ((.metrics.dropped_iterations.values.count // 0) == 0)
                   and ((.metrics.http_req_failed.values.rate // 0) < 0.001)
                   and ((.metrics.http_req_duration.values["p(99)"] // 9999) < 200)
                then "1" else "0" end' "$f" 2>/dev/null || echo 0)
            if [[ "$ok" == "1" ]]; then best="$rate"; else break; fi
        done
        if [[ -n "$best" ]]; then
            echo "  $phase: clean ceiling at $best req/s"
        else
            echo "  $phase: no clean rate — the generator is the limit"
        fi
    done
    echo
    echo "Operating rule: the sweeps run at a TENTH of the ceiling of the"
    echo "ceiling phase. That margin is what allows us to state that the"
    echo "generator never influenced the measurement."
    echo
    echo "To check by hand in the peak CPU column:"
    echo "  varnish  must stay below 60% of its core budget."
    echo "           If it saturates, the cache becomes the bottleneck and"
    echo "           we would be measuring it instead of the application server."
    echo "  k6       if it exceeds 90%, the ceiling is the generator."
    echo "  app      if it saturates the CPU before the thread pool"
    echo "           fills up, the limit is the GIL and not the pool."
    echo
    echo "Full logs and JSON summaries in: $OUT"
} >> "$REPORT"

echo
cat "$REPORT"
echo
log "report: $REPORT"