#!/usr/bin/env bash
# Build the arXiv submission package of the paper without touching its sources.
#
#   paper/make_arxiv.sh            (from anywhere inside the repository)
#
# Output, in paper/arxiv/ (ignored by git):
#   undertow-arxiv.zip   the package: main.tex, sections/, figures/ (PDF + .caption.tex),
#                        main.bbl, llncs.cls, splncs04.bst, orcidlink.sty
#   package/             the same files, unzipped
#   check/               the zip unpacked in an empty folder and compiled as arXiv does
#                        (pdflatex twice, no bibtex)
#   abstract.txt         plain-text abstract for the arXiv form
#   metadata.txt         title, author, Comments, pages, figures
#
# Requirements: TeX Live (pdflatex, bibtex, kpsewhich), poppler (pdftotext, pdfinfo), zip,
# curl, and arxiv_latex_cleaner in a virtualenv outside the repository:
#   python3 -m venv ~/.venvs/arxiv-cleaner && ~/.venvs/arxiv-cleaner/bin/pip install arxiv_latex_cleaner
#
# Environment:
#   ARXIV_CLEANER   path of the arxiv_latex_cleaner executable
#                   (default ~/.venvs/arxiv-cleaner/bin/arxiv_latex_cleaner)
#   REF_PDF         PDF the compiled text must match (default: the v1.0.2 release PDF,
#                   downloaded once into paper/arxiv/)
#   EXPECTED_PAGES  page count the compiled package must have (default 31)
set -euo pipefail

REPO=$(cd "$(dirname "$0")/.." && pwd)
PAPER="$REPO/paper"
OUT="$PAPER/arxiv"
CLEANER=${ARXIV_CLEANER:-$HOME/.venvs/arxiv-cleaner/bin/arxiv_latex_cleaner}
REF_URL=https://github.com/and18/undertow/releases/download/v1.0.2/undertow-paper-v1.0.2.pdf
REF_PDF=${REF_PDF:-$OUT/reference-v1.0.2.pdf}
EXPECTED_PAGES=${EXPECTED_PAGES:-31}
ZIP="$OUT/undertow-arxiv.zip"

die() { echo "make_arxiv: $*" >&2; exit 1; }
[ -x "$CLEANER" ] || die "arxiv_latex_cleaner not found at $CLEANER (see the header of this script)"
for tool in pdflatex bibtex kpsewhich pdftotext pdfinfo zip unzip curl python3; do
  command -v "$tool" >/dev/null || die "$tool not found"
done

mkdir -p "$OUT"
rm -rf "$OUT/bbl" "$OUT/stage" "$OUT/stage_arXiv" "$OUT/package" "$OUT/check" "$OUT/check3" "$ZIP"

# ── 1. main.bbl, generated by BibTeX from the unmodified sources ───────────────
echo "== main.bbl"
mkdir -p "$OUT/bbl"
cp "$PAPER/main.tex" "$PAPER/references.bib" "$OUT/bbl/"
cp -r "$PAPER/sections" "$OUT/bbl/"
sed -i "s|\.\./figures/paper/|$REPO/figures/paper/|g" "$OUT/bbl/main.tex"
(cd "$OUT/bbl" && pdflatex -interaction=nonstopmode -halt-on-error -draftmode main.tex >/dev/null \
  && bibtex main >/dev/null) || die "BibTeX run failed, see $OUT/bbl/main.log and main.blg"

# ── 2. staging copy: figure paths rewritten, claim markers removed ────────────
echo "== staging"
mkdir -p "$OUT/stage"
cp "$PAPER/main.tex" "$OUT/stage/"
cp -r "$PAPER/sections" "$OUT/stage/"
python3 - "$OUT/stage" <<'PY'
import pathlib, re, sys
stage = pathlib.Path(sys.argv[1])

main = stage / "main.tex"
text = main.read_text()
# arXiv does not accept ../: the figures move to figures/ inside the package.
text, n = re.subn(r"\.\./figures/paper/", "figures/", text)
assert n >= 2, f"expected the 2 figure paths of \\undertowfig in main.tex, found {n}"
# The marker macro and its switch are not needed once every \claim{...} is gone.
text, n = re.subn(r"\\let\\claim\\relax\n.*?\\newcommand\{\\claim\}\[1\]\{\}\n\\fi\n", "",
                  text, flags=re.S)
assert n == 1, "claim-marker block not found in main.tex"
main.write_text(text)

# \claim{ID} expands to nothing: deleting it (and only it) leaves the typeset text unchanged.
for tex in stage.rglob("*.tex"):
    t = tex.read_text()
    t = re.sub(r"\\claim\{[^{}]*\}", "", t)
    tex.write_text(t)
PY

# ── 3. comments out with arxiv_latex_cleaner ──────────────────────────────────
echo "== arxiv_latex_cleaner"
"$CLEANER" "$OUT/stage" >/dev/null
mv "$OUT/stage_arXiv" "$OUT/package"
rm -rf "$OUT/stage"

# ── 4. figures used by the paper, support files ───────────────────────────────
echo "== figures and support files"
mkdir -p "$OUT/package/figures"
mapfile -t STEMS < <(grep -ho '\\undertowfig\(\[[^]]*\]\)\?{[^}]*}' "$OUT/package/sections/"*.tex \
                     | sed 's/.*{\([^}]*\)}$/\1/')
[ "${#STEMS[@]}" -gt 0 ] || die "no \\undertowfig found in the cleaned sections"
for stem in "${STEMS[@]}"; do
  for f in "$stem.pdf" "$stem.caption.tex"; do
    [ -f "$REPO/figures/paper/$f" ] || die "missing figures/paper/$f (run make figures)"
    cp "$REPO/figures/paper/$f" "$OUT/package/figures/"
  done
done
cp "$OUT/bbl/main.bbl" "$OUT/package/main.bbl"
for f in llncs.cls splncs04.bst orcidlink.sty; do
  src=$(kpsewhich "$f") || die "kpsewhich cannot find $f"
  cp "$src" "$OUT/package/"
done
rm -rf "$OUT/bbl"

# ── 5. content checks on the package ──────────────────────────────────────────
echo "== content checks"
python3 - "$OUT/package" "$REPO" <<'PY'
import pathlib, re, sys
pkg, repo = pathlib.Path(sys.argv[1]), sys.argv[2]
ours = [p for p in pkg.rglob("*") if p.suffix in (".tex", ".bbl")]
problems = []
for p in ours:
    for i, line in enumerate(p.read_text().splitlines(), 1):
        # a bare % (end-of-line guard, no text) is not a comment and must stay
        if re.search(r"(?<!\\)%.*\S", line):
            problems.append(f"{p.relative_to(pkg)}:{i}: comment: {line.strip()}")
        for bad in (r"\\claim", r"claims", r"docs/", r"\bPAM\b", r"\.\./", repo, r"/home/"):
            if re.search(bad, line):
                problems.append(f"{p.relative_to(pkg)}:{i}: '{bad}': {line.strip()}")
for p in pkg.rglob("*"):  # third-party files: no local paths either
    if p.is_file() and p.suffix in (".cls", ".bst", ".sty") and ("/home/" in p.read_text(errors="replace")):
        problems.append(f"{p.relative_to(pkg)}: local path")
if problems:
    sys.exit("make_arxiv: content check failed\n  " + "\n  ".join(problems))
PY

# ── 6. zip ────────────────────────────────────────────────────────────────────
echo "== zip"
(cd "$OUT/package" && find . -type f | sed 's|^\./||' | LC_ALL=C sort | zip -X -q "$ZIP" -@)

# ── 7. compile as arXiv does: empty folder, pdflatex twice, no bibtex ─────────
echo "== compile check"
mkdir -p "$OUT/check"
unzip -q "$ZIP" -d "$OUT/check"
for pass in 1 2; do
  (cd "$OUT/check" && pdflatex -interaction=nonstopmode -halt-on-error main.tex >/dev/null) \
    || die "pdflatex pass $pass failed, see $OUT/check/main.log"
done
LOG="$OUT/check/main.log"
! grep -q '^!' "$LOG" || die "errors in $LOG"
! grep -q 'undefined' "$LOG" || { grep 'undefined' "$LOG" >&2; die "undefined references or citations"; }
# The second pass may still warn that labels changed (they did, between pass 1 and 2).
# The output is final if a third pass, on a copy, leaves the .aux unchanged.
if grep -q 'Rerun to get' "$LOG"; then
  cp -r "$OUT/check" "$OUT/check3"
  (cd "$OUT/check3" && pdflatex -interaction=nonstopmode -halt-on-error main.tex >/dev/null) \
    || die "third pdflatex pass failed"
  cmp -s "$OUT/check/main.aux" "$OUT/check3/main.aux" \
    || die "cross-references not stable after two passes (.aux changes on a third)"
  rm -rf "$OUT/check3"
  echo "   rerun warning after pass 2: a third pass leaves main.aux unchanged, output is final"
fi
pdftotext "$OUT/check/main.pdf" "$OUT/check/main.txt"
! grep -q '??' "$OUT/check/main.txt" || die "'??' in the compiled text"
PAGES=$(pdfinfo "$OUT/check/main.pdf" | awk '/^Pages:/ {print $2}')
[ "$PAGES" = "$EXPECTED_PAGES" ] || die "$PAGES pages, expected $EXPECTED_PAGES"

[ -f "$REF_PDF" ] || curl -sSfL -o "$REF_PDF" "$REF_URL" || die "cannot download $REF_URL"
pdftotext "$REF_PDF" "$OUT/check/reference.txt"
if ! diff -q "$OUT/check/reference.txt" "$OUT/check/main.txt" >/dev/null; then
  diff "$OUT/check/reference.txt" "$OUT/check/main.txt" | head -40 >&2
  die "compiled text differs from $(basename "$REF_PDF")"
fi
echo "   no errors, no '??', $PAGES pages, text identical to $(basename "$REF_PDF")"

# ── 8. abstract.txt and metadata.txt ──────────────────────────────────────────
echo "== abstract and metadata"
NFIG=${#STEMS[@]}
python3 - "$OUT" "$PAGES" "$NFIG" <<'PY'
import pathlib, re, sys
out, pages, nfig = pathlib.Path(sys.argv[1]), sys.argv[2], int(sys.argv[3])
pkg = out / "package"

def plain(tex):
    t = re.sub(r"(?<!\\)%[^\n]*", "", tex)       # guard %s left by the cleaner
    t = t.replace("$", "").replace("---", "-").replace("--", "-")
    t = t.replace("~", " ").replace(r"\%", "%").replace(r"\,", " ")
    t = re.sub(r"\s+", " ", t).strip()
    leftover = re.findall(r"[\\{}]", t)
    assert not leftover, f"LaTeX left in plain text: {leftover}: {t}"
    return t

abstract = plain((pkg / "sections" / "00-abstract.tex").read_text())
assert len(abstract) < 1920, f"abstract is {len(abstract)} characters, arXiv limit 1920"
(out / "abstract.txt").write_text(abstract + "\n")

main = (pkg / "main.tex").read_text()
title = plain(re.search(r"\\title\{(.*?)\}\n", main, re.S).group(1))
author = re.search(r"\\author\{([^\\}]*)", main).group(1).strip()
comments = (f"{pages} pages, {nfig} figures. Code, configurations, derived data and figure "
            "scripts: https://github.com/and18/undertow, archived on Zenodo "
            "(https://doi.org/10.5281/zenodo.23127696)")
(out / "metadata.txt").write_text(
    f"Title: {title}\nAuthors: {author}\nComments: {comments}\n"
    f"Pages: {pages}\nFigures: {nfig}\n")
print(f"   abstract: {len(abstract)} characters; {pages} pages, {nfig} figures")
PY

echo "== package contents"
unzip -l "$ZIP"
